### PR TITLE
Significant Refactoring

### PR DESCRIPTION
**Pull request by JeffSteinbok**
## Summary
* This change refactors a significant portion of the code for future flexibility. 
* Created separate files for each Dreo HA class
* Created seperate PyDreo classes for each device type (Air Circulator, Purifier, Tower Fan, etc...)
* Made ChefMaker a subclass of SwitchEntity and took the Power switch out of the list so we shouldn't get separate power toggles for each device
* Fully support Ceiling fan light switch
* More (but incomplete) UTs

## CoPilot Generated
This pull request includes several changes to the `custom_components/dreo` module to improve the integration with Dreo devices. The most important changes involve renaming variables and functions for consistency, adding support for air purifiers, and refactoring the code to use a unified manager class.

### Codebase Refactoring:
* [`custom_components/dreo/__init__.py`](diffhunk://#diff-0ae7123b22240ee3372d4a3446b65e5039bb6590dcefd68669d2827dd1630f35L10-R10): Renamed `manager` to `pydreo_manager` and updated the logic to use the new `PyDreo` manager class. Removed the `process_devices` function and directly handled device types in the `async_setup_entry` method. [[1]](diffhunk://#diff-0ae7123b22240ee3372d4a3446b65e5039bb6590dcefd68669d2827dd1630f35L10-R10) [[2]](diffhunk://#diff-0ae7123b22240ee3372d4a3446b65e5039bb6590dcefd68669d2827dd1630f35R33-R80) [[3]](diffhunk://#diff-0ae7123b22240ee3372d4a3446b65e5039bb6590dcefd68669d2827dd1630f35L111-L146)
* [`custom_components/dreo/const.py`](diffhunk://#diff-d6041dfacceac050806ba5a1b490c36e0b6ebda7459b9934c251d0de3ee23156L7-R7): Removed old device type constants (`DREO_FANS`, `DREO_HEATERS`, etc.) and added `PYDREO_MANAGER`.

### Device Support:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R39): Added support for `Air Purifiers` to the list of supported fan types.
* [`custom_components/dreo/dreoairconditioner.py`](diffhunk://#diff-605c3e0decab2998a9a3fb3838b8487ca11c4753903af91b9d1fd751b5fbfc4eR1-R389): Added a new file to support climate control for Dreo air conditioners, including detailed implementation for various HVAC modes and features.

### Diagnostics and Configuration:
* [`custom_components/dreo/diagnostics.py`](diffhunk://#diff-5d190e6bae60cd24dec56cc21919c93c1f8479078ac70c4879a9c4b56f089d1aL16-R16): Updated diagnostics to use `pydreo_manager` and simplified the data structure for device counts and raw device lists. [[1]](diffhunk://#diff-5d190e6bae60cd24dec56cc21919c93c1f8479078ac70c4879a9c4b56f089d1aL16-R16) [[2]](diffhunk://#diff-5d190e6bae60cd24dec56cc21919c93c1f8479078ac70c4879a9c4b56f089d1aL40-R47)
* [`custom_components/dreo/config_flow.py`](diffhunk://#diff-5503d802c407218607aa97a196a7a9a185d2bc8587fc8e4dd7cf04463c14b617L52-R53): Renamed `manager` to `pydreo_manager` in the user configuration flow.

### File Renaming:
* [`custom_components/dreo/dreobasedevice.py`](diffhunk://#diff-fec43c778d82d67c9c938afc6115a014df5583b5e98f631d5c163caf7fed11d3L2-R16): Renamed from `basedevice.py` and updated references to use `pydreo_device` instead of `device`. [[1]](diffhunk://#diff-fec43c778d82d67c9c938afc6115a014df5583b5e98f631d5c163caf7fed11d3L2-R16) [[2]](diffhunk://#diff-fec43c778d82d67c9c938afc6115a014df5583b5e98f631d5c163caf7fed11d3L30-R30)

### CODE REVIEW

**Comment by JeffSteinbok** [comment]
@iRonin  - Can you please confirm this works for ChefMaker?

**Comment by iRonin** [comment]
image

All the three off buttons are inactive on my fans as compared to the master branch.

**Comment by iRonin** [comment]
The buttons on the ChefMaker does not work either
image

**Comment by iRonin** [comment]
image

AC buttons do not work either.

Seems ChefMaker does not work on master either - need to check it further.

**Comment by iRonin** [comment]
ChefMaker's buttons were broken somewhere between these two commits. Maybe it'll be easier for you @JeffSteinbok to say what could cause it.

image

**Comment by JeffSteinbok** [comment]
@iRonin  surprised that all the switches failed.  Can you please send me some logs?  Curious what's going on there. 
I had some switch issues with I thought I got fixed last night.

**Comment by iRonin** [comment]
@JeffSteinbok emailed the logs.

Even ChefMaker does not work on this branch. For all such entities I get: This entity is no longer being provided by the dreo integration. If the entity is no longer in use, delete it in settings.

**Comment by JeffSteinbok** [comment]
@iRonin is there any chance you can have a look at the code and debug a little bit? I totally changed how the chef maker get set up. It's now a subclass of switch entity. I wonder if something went wrong when it gets added, which causes the whole platform to not start

**Comment by iRonin** [comment]
Where's AI when we need it the most.

I'm not overly familiar with HA architecture but sure, if I have time I'll have a look. 

However, not sure why you'd want to make ChefMaker a subclass of switch - I implemented a couple of switches for it but there is more features in the API @JeffSteinbok

**Comment by JeffSteinbok** [comment]
Reason being that there is no other HA platform that represents a cooker.
So, I made the "Power" switch the "Device" and all other switches are "features".
It fits the other models pretty well.

**Comment by iRonin** [comment]
> Reason being that there is no other HA platform that represents a cooker.

Yeah, there is a proposal [here](https://github.com/home-assistant/architecture/discussions/501)

**Comment by JeffSteinbok** [comment]
> > Reason being that there is no other HA platform that represents a cooker.
> 
> Yeah, there is a proposal [here](https://github.com/home-assistant/architecture/discussions/501)

Once that's done, will happily change it.  Doing it this way solved the problem of having the Power switch show up for everything.

**Comment by JeffSteinbok** [comment]
Ok, from your logs I see a bug (also need to see why I'm seeing "entity None" everywhere).  
Looks like I had this wrong and we considered all devices Fans.   Woops.

This was AI writing the line and it missed a bit.  Anyway, fixed in latest commit.

Try again?

    fan_entities_ha = []
    for pydreo_device in pydreo_manager.devices:
        if (pydreo_device.type == DreoDeviceType.TOWER_FAN or
            pydreo_device.type == DreoDeviceType.AIR_CIRCULATOR or
            pydreo_device.type):
            fan_entities_ha.append(DreoFanHA(pydreo_device))

**Comment by iRonin** [comment]
46f21ee3a6d0926a1894658ff1d5793bbf6fb2ab is where things start breaking

**Comment by iRonin** [comment]
Prior to 46f21ee3a6d0926a1894658ff1d5793bbf6fb2ab only ChefMaker and the AC is not working.

**Comment by JeffSteinbok** [comment]
What is current state on your system?

**Comment by iRonin** [comment]
> What is current state on your system?

Not sure what you're asking about - I'm testing this on a test instance and putting different commits. On my home one I've got something that I know that works and I'm not touching it haha but there everything is working.

State for b0c79458a2228e67a096abca457b377bff50989c
Screenshot 2024-09-05 at 15 43 44

State for 46f21ee3a6d0926a1894658ff1d5793bbf6fb2ab
image

State for 3fb486113954d30ba3401a86bb8c46f7a2f49213
image

**Comment by JeffSteinbok** [comment]
I've added some stub unit and integration tests for ChefMaker.  I'm not sure what's up with yours right now.  
The log from before is old, can you please send me an updated one.  I'm looking for something that looks like the Switch platform failing to setup.

**Comment by iRonin** [comment]
I realized overnight that the entities I was posting out as not working are the switches you removed and ChefMaker power was replaced with switch too. I liked the individual power buttons though as a quick toggle.

**Comment by iRonin** [comment]
Seems the ChefMaker is good but the A/C is broken. Will look into this.

**Comment by Monsterray** [comment]
Taking a look after downloading the main branch it seems that my Macro Pro S isn't showing up as a device in HA.

**Pull request merged**
