### PR TITLE
Fix AC WIP

### PR DESCRIPTION
**Pull request by iRonin**
# Work In Progress

- [x] Display Off button has on/off swapped with API `light on` status
- [x] The main entity is no longer being provided by the dreo integration
- [x] Fix child lock button
- [ ] Current temperature not matching units

### CODE REVIEW

**Comment by iRonin** [comment]
@JeffSteinbok if you know from the top of your head what may have cause this please let me know when you have a moment:

image

**Comment by JeffSteinbok** [comment]
Are there errors in the logs?

**Comment by JeffSteinbok** [comment]
Also suggest adding some tests for ACs

**Comment by iRonin** [comment]
No errors. Some toggles are working but not the main entity.
I guess the `Device Power` has been removed as well as the switch called `Electric AC`?

image

Here is how the (previous) working version looks like:
image

**Comment by JeffSteinbok** [comment]
You shouldn’t need device power for a Climate entity as it supports power natively.

Look in the logs/code for why the AC climate entity was not loaded. It’s possible the device type didn’t match and it didn’t get added to the list.

Easiest way to do this may be to add an integration test similar to what I added yesterday for ChefMaker.

-Jeff

On Sep 6, 2024, at 8:18 AM, Cyprian Kowalczyk ***@***.***> wrote:

﻿

No errors. Some toggles are working but not the main entity.
I guess the Device Power has been removed as well as the switch called Electric AC?

image.png (view on web)<https://github.com/user-attachments/assets/c02b67d7-ee31-404f-9bbd-bc71c404daf5>

Here is how the (previous) working version looks like:
image.png (view on web)<https://github.com/user-attachments/assets/44602661-95d5-4f03-afed-a8525da93073>

**Comment by iRonin** [comment]
It seems it's being now identified as `pyDreoBaseDevice`

**Comment by iRonin** [comment]
Maybe you can spot something in the logs:

```
2024-09-06 17:45:01.662 DEBUG (SyncWorker_0) [pydreo] pydreo._process_devices
2024-09-06 17:45:01.662 DEBUG (SyncWorker_0) [pydreo] New device list initialized
2024-09-06 17:45:01.662 DEBUG (SyncWorker_0) [pydreo] Found device with model DR-HAC005S
2024-09-06 17:45:01.662 DEBUG (SyncWorker_0) [pydreo] Prefix DR-HAC assigned from model DR-HAC005S
2024-09-06 17:45:01.662 DEBUG (SyncWorker_0) [pydreo] Device DR-HAC005S found!
2024-09-06 17:45:01.663 DEBUG (SyncWorker_0) [pydreo] load_device_state: Electric AC, enabled: True
2024-09-06 17:45:01.663 DEBUG (SyncWorker_0) [pydreo] Calling Dreo API: {devicestate}
2024-09-06 17:45:01.663 DEBUG (SyncWorker_0) [pydreo] =======call_api=============================
2024-09-06 17:45:01.663 DEBUG (SyncWorker_0) [pydreo] [get] calling '/api/user-device/device/state' api
2024-09-06 17:45:01.663 DEBUG (SyncWorker_0) [pydreo] API call URL: 
  https://app-api-us.dreo-cloud.com/api/user-device/device/state
2024-09-06 17:45:01.663 DEBUG (SyncWorker_0) [pydreo] API call headers: 
  {"ua": "dreo/2.8.2", "lang": "en", "content-type": "application/json; charset=UTF-8", "accept-encoding": "gzip", "user-agent": "okhttp/4.9.1", "authorization": "##_REDACTED_##"}
2024-09-06 17:45:01.663 DEBUG (SyncWorker_0) [pydreo] API call json: 
  {"deviceSn": "sn123123"}
2024-09-06 17:45:02.802 DEBUG (SyncWorker_0) [pydreo] API response: 

  {"code": 0, "msg": "OK", "data": {"mixed": {"wifi_rssi": {"state": -43, "timestamp": 1725642084}, "poweron": {"state": true, "timestamp": 1725642084}, "scheid": {"state": 231789745, "timestamp": 1725642084}, "timeron": {"state": {"du": 0, "ts": 1724691562}, "timestamp": null}, "coolcruvendts": {"state": 0, "timestamp": 1725642084}, "scheon": {"state": false, "timestamp": 1725642084}, "mcuon": {"state": true, "timestamp": 1725642084}, "templevel": {"state": 86, "timestamp": 1725642084}, "mode": {"state": 1, "timestamp": 1725642497}, "network_latency": {"state": 124, "timestamp": 1725642084}, "rhlevel": {"state": 80, "timestamp": 1725642084}, "module_hardware_model": {"state": "HeFi", "timestamp": 1725642084}, "mcu_firmware_version": {"state": "1.0.72", "timestamp": 1725642084}, "oscmode": {"state": 2, "timestamp": 1725642084}, "temperature": {"state": 88, "timestamp": 1725644016}, "module_hardware_mac": {"state": "mac123123", "timestamp": 1725642084}, "reachtarget": {"state": 0, "timestamp": 1725642084}, "muteon": {"state": true, "timestamp": 1725642084}, "lighton": {"state": false, "timestamp": 1725642084}, "mcu_hardware_model": {"state": "SC95F8613B/US", "timestamp": 1725642084}, "wifi_ssid": {"state": "wifiid", "timestamp": 1724691562}, "windlevel": {"state": 3, "timestamp": 1725642503}, "tempunit": {"state": 1, "timestamp": 1725642084}, "sleeptempoffset": {"state": 0, "timestamp": 1725642084}, "module_firmware_version": {"state": "3.2.16", "timestamp": 1725642084}, "wrong": {"state": 0, "timestamp": 1725642084}, "connected": {"state": true, "timestamp": 1725642084}, "timeroff": {"state": {"du": 0, "ts": 1724691562}, "timestamp": null}, "_ota": {"state": 2, "timestamp": 1725642084}, "filterthr": {"state": 600, "timestamp": 1725642084}, "coolcurveconf": {"state": "NULL", "timestamp": 1725642084}, "rh": {"state": 65, "timestamp": 1725644694}, "ecopauserate": {"state": 30, "timestamp": 1725642084}, "childlockon": {"state": false, "timestamp": 1725642084}, "worktime": {"state": 563, "timestamp": 1725644104}}, "sn": "sn123123", "productId": "123123123", "region": "us-east-2/emq"}} 
 
2024-09-06 17:45:02.803 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice:update_state: {'wifi_rssi': {'state': -43, 'timestamp': 1725642084}, 'poweron': {'state': True, 'timestamp': 1725642084}, 'scheid': {'state': 231789745, 'timestamp': 1725642084}, 'timeron': {'state': {'du': 0, 'ts': 1724691562}, 'timestamp': None}, 'coolcruvendts': {'state': 0, 'timestamp': 1725642084}, 'scheon': {'state': False, 'timestamp': 1725642084}, 'mcuon': {'state': True, 'timestamp': 1725642084}, 'templevel': {'state': 86, 'timestamp': 1725642084}, 'mode': {'state': 1, 'timestamp': 1725642497}, 'network_latency': {'state': 124, 'timestamp': 1725642084}, 'rhlevel': {'state': 80, 'timestamp': 1725642084}, 'module_hardware_model': {'state': 'HeFi', 'timestamp': 1725642084}, 'mcu_firmware_version': {'state': '1.0.72', 'timestamp': 1725642084}, 'oscmode': {'state': 2, 'timestamp': 1725642084}, 'temperature': {'state': 88, 'timestamp': 1725644016}, 'module_hardware_mac': {'state': 'mac123123', 'timestamp': 1725642084}, 'reachtarget': {'state': 0, 'timestamp': 1725642084}, 'muteon': {'state': True, 'timestamp': 1725642084}, 'lighton': {'state': False, 'timestamp': 1725642084}, 'mcu_hardware_model': {'state': 'SC95F8613B/US', 'timestamp': 1725642084}, 'wifi_ssid': {'state': 'wifiid', 'timestamp': 1724691562}, 'windlevel': {'state': 3, 'timestamp': 1725642503}, 'tempunit': {'state': 1, 'timestamp': 1725642084}, 'sleeptempoffset': {'state': 0, 'timestamp': 1725642084}, 'module_firmware_version': {'state': '3.2.16', 'timestamp': 1725642084}, 'wrong': {'state': 0, 'timestamp': 1725642084}, 'connected': {'state': True, 'timestamp': 1725642084}, 'timeroff': {'state': {'du': 0, 'ts': 1724691562}, 'timestamp': None}, '_ota': {'state': 2, 'timestamp': 1725642084}, 'filterthr': {'state': 600, 'timestamp': 1725642084}, 'coolcurveconf': {'state': 'NULL', 'timestamp': 1725642084}, 'rh': {'state': 65, 'timestamp': 1725644694}, 'ecopauserate': {'state': 30, 'timestamp': 1725642084}, 'childlockon': {'state': False, 'timestamp': 1725642084}, 'worktime': {'state': 563, 'timestamp': 1725644104}}
2024-09-06 17:45:02.803 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: poweron-> True
2024-09-06 17:45:02.803 DEBUG (SyncWorker_0) [pydreo] PyDreoAC(Electric AC):update_state: {'wifi_rssi': {'state': -43, 'timestamp': 1725642084}, 'poweron': {'state': True, 'timestamp': 1725642084}, 'scheid': {'state': 231789745, 'timestamp': 1725642084}, 'timeron': {'state': {'du': 0, 'ts': 1724691562}, 'timestamp': None}, 'coolcruvendts': {'state': 0, 'timestamp': 1725642084}, 'scheon': {'state': False, 'timestamp': 1725642084}, 'mcuon': {'state': True, 'timestamp': 1725642084}, 'templevel': {'state': 86, 'timestamp': 1725642084}, 'mode': {'state': 1, 'timestamp': 1725642497}, 'network_latency': {'state': 124, 'timestamp': 1725642084}, 'rhlevel': {'state': 80, 'timestamp': 1725642084}, 'module_hardware_model': {'state': 'HeFi', 'timestamp': 1725642084}, 'mcu_firmware_version': {'state': '1.0.72', 'timestamp': 1725642084}, 'oscmode': {'state': 2, 'timestamp': 1725642084}, 'temperature': {'state': 88, 'timestamp': 1725644016}, 'module_hardware_mac': {'state': '123123123', 'timestamp': 1725642084}, 'reachtarget': {'state': 0, 'timestamp': 1725642084}, 'muteon': {'state': True, 'timestamp': 1725642084}, 'lighton': {'state': False, 'timestamp': 1725642084}, 'mcu_hardware_model': {'state': 'SC95F8613B/US', 'timestamp': 1725642084}, 'wifi_ssid': {'state': 'wifi123', 'timestamp': 1724691562}, 'windlevel': {'state': 3, 'timestamp': 1725642503}, 'tempunit': {'state': 1, 'timestamp': 1725642084}, 'sleeptempoffset': {'state': 0, 'timestamp': 1725642084}, 'module_firmware_version': {'state': '3.2.16', 'timestamp': 1725642084}, 'wrong': {'state': 0, 'timestamp': 1725642084}, 'connected': {'state': True, 'timestamp': 1725642084}, 'timeroff': {'state': {'du': 0, 'ts': 1724691562}, 'timestamp': None}, '_ota': {'state': 2, 'timestamp': 1725642084}, 'filterthr': {'state': 600, 'timestamp': 1725642084}, 'coolcurveconf': {'state': 'NULL', 'timestamp': 1725642084}, 'rh': {'state': 65, 'timestamp': 1725644694}, 'ecopauserate': {'state': 30, 'timestamp': 1725642084}, 'childlockon': {'state': False, 'timestamp': 1725642084}, 'worktime': {'state': 563, 'timestamp': 1725644104}}
2024-09-06 17:45:02.804 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: temperature-> 88
2024-09-06 17:45:02.804 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: templevel-> 86
2024-09-06 17:45:02.804 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: mode-> 1
2024-09-06 17:45:02.804 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: windlevel-> 3
2024-09-06 17:45:02.804 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: oscmode-> 2
2024-09-06 17:45:02.804 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: muteon-> True
2024-09-06 17:45:02.804 DEBUG (SyncWorker_0) [pydreo] State value (devon) not present.  Device: Electric AC
2024-09-06 17:45:02.804 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: timeron-> {'du': 0, 'ts': 1724691562}
2024-09-06 17:45:02.804 DEBUG (SyncWorker_0) [pydreo] State value (cooldown) not present.  Device: Electric AC
2024-09-06 17:45:02.805 DEBUG (SyncWorker_0) [pydreo] State value (ptcon) not present.  Device: Electric AC
2024-09-06 17:45:02.805 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: lighton-> False
2024-09-06 17:45:02.805 DEBUG (SyncWorker_0) [pydreo] State value (ctlstatus) not present.  Device: Electric AC
2024-09-06 17:45:02.805 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: timeroff-> {'du': 0, 'ts': 1724691562}
2024-09-06 17:45:02.805 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: childlockon-> False
2024-09-06 17:45:02.805 DEBUG (SyncWorker_0) [pydreo] State value (tempoffset) not present.  Device: Electric AC
2024-09-06 17:45:02.805 DEBUG (SyncWorker_0) [pydreo] State value (fixedconf) not present.  Device: Electric AC
2024-09-06 17:45:02.805 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: rh-> 65
2024-09-06 17:45:02.805 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: rhlevel-> 80
2024-09-06 17:45:02.805 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: worktime-> 563
2024-09-06 17:45:02.805 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice(<PyDreoAC:123123123:Electric AC>):get_state_update_value: reachtarget-> 0
```

**Comment by JeffSteinbok** [comment]
Found the bug!
https://github.com/JeffSteinbok/hass-dreo/pull/190

Was missing 1 line:
async_add_entities(climate_entities_ha)

Also added stub tests for AC.  You can add specific commands if you have time, else I will later.

**Comment by iRonin** [comment]
The only thing missing now is the `Child Lock` toggle:

image

Logs look good, it's just the button is disabled:

```
2024-09-06 18:10:54.492 DEBUG (SyncWorker_1) [pydreo] pyDreoBaseDevice(<PyDreoAC:1791507716082036738:Electric AC>):get_state_update_value: childlockon-> False
```

**Comment by iRonin** [comment]
I think I see the issue

**Comment by iRonin** [comment]
Last issue is incorrect current temperature reading/units

Screenshot 2024-09-06 at 14 24 01

**Comment by iRonin** [comment]
@JeffSteinbok please check my above comment and maybe you'll know if it's HA's issue or the plugin's - when I change temp units to `F` in HA then all temperature readings are correct (the above comment had the units as `C`):

image

**Comment by JeffSteinbok** [comment]
Looks good; let's get this in!  I'll get mine in which moves some of those test files around, then you can add yours on top.  Should go easy.

**Review by JeffSteinbok — APPROVED** [review]

**Comment by JeffSteinbok** [comment]
@iRonin  Were you going to complete the work for this PR or want me to pull in the diffs and apply?

**Comment by iRonin** [comment]
@JeffSteinbok the last time I had a look there was no conflicts and I though I'll getting this in. Not sure if I manage to have a look at this today.

**Comment by iRonin** [comment]
@JeffSteinbok done

**Pull request merged**
