### PR TITLE
Add support for Dreo Air Conditioners

### PR DESCRIPTION
**Pull request by iRonin**
~~This is not fully working yet.~~ It doesn't seem to break anything though. 
I've got couple of DR-HTF004S and they continue to work.
The AC model is DR-HAC005S.

The following controls work:
 - Child Lock
 - Device Power
 - Display Auto Off
 - Panel Sound

The `temperature` is reported correctly.

Not sure if heaters have it but the AC reports the water tank level in the Dreo app, as well as have a Cleaning Reminder and Usage.

@JeffSteinbok if you could point me to how to debug the power control and how to make the modes work it would be fantastic 🙇‍♂️ 

Screenshot 2024-05-26 at 12 02 50

image
image
image
image

image

### CODE REVIEW

**Comment by JeffSteinbok** [comment]
Thanks!  For the new features and such, you'll likely need to capture a packet trace, which unfortunately is hard.
See https://github.com/JeffSteinbok/hass-dreo/blob/main/contributing.md for more info

**Comment by iRonin** [comment]
@JeffSteinbok maybe you could help me out with something simpler - I've got the AC control showing up in HA and it does control the unit but it does not change its state.
The unit reports modes as: 1 (Cool), 2 (Dry), 3 (Fan only), 5 (Cool on Eco)

I'm yet to figure out how to make it properly work in HA - I suspect HA stores AC state as string but I receive and should send it as number, somehow.

image

**Comment by iRonin** [comment]
Still some issues with target/current temp.
Can't set humidity level
Would like to disable temp select on fan only
Would like to have different temp ranges for ECO preset.

Screenshot 2024-05-27 at 17 49 37
Screenshot 2024-05-27 at 17 49 45

**Comment by iRonin** [comment]
image
image
image
image

**Comment by iRonin** [comment]
@JeffSteinbok this is pretty much ready, won't be adding more features.

**Pull request merged**
