### PR TITLE
UnitTest Cleanup & Samples

### PR DESCRIPTION
**Pull request by JeffSteinbok**
This pull request includes several changes to the PyDreo library and its associated tests. The most important changes involve refactoring error handling in the `pydreofan.py` file and updating constants in `constant.py`. Additionally, there are updates to unit tests and removal of unused code.

### Refactoring and Error Handling Improvements:

* Replaced `_LOGGER.error` calls with appropriate exceptions (`ValueError` or `NotImplementedError`) in various methods to improve error handling in `pydreofan.py`.

### Unit Tests:

* Added a README file to describe the setup and structure of unit tests in the `tests/pydreo` directory.
* Added new API response JSON files for device state tests (`get_device_state_HAF004S_1.json` and `get_device_state_HTF008S_1.json`). [[1]](diffhunk://#diff-96cd7b764a81731c9e9118884a3e8d93e7e7ad071228b7561708e98099a06ff3R1-R123) [[2]](diffhunk://#diff-0a5eb499910d53e0caf079230a1946532861a9f6b2c25dbb41a48dd511b181a9R1-R101)

### Code Cleanup:

* Removed unused imports and constants in `sensor.py`. [[1]](diffhunk://#diff-4bb80535354eb40cdec9bbd5e05ab6aeba5e9e377b139fef4a49d00a2f10dea5L15) [[2]](diffhunk://#diff-4bb80535354eb40cdec9bbd5e05ab6aeba5e9e377b139fef4a49d00a2f10dea5L39-R38)
* Removed obsolete API definitions from `dreo.yaml` and `PyDreo.yaml` files. [[1]](diffhunk://#diff-1ffb3169bc38b4b60f52ded02ff40702210b20f950ad56f2052dd9a5af67c515L1-L33) [[2]](diffhunk://#diff-9635e321d7e19bf5d4c5722808d71997485ef9718cbd2cf77479ed8ca7b53306L1-L6)

### CODE REVIEW

**Comment by JeffSteinbok** [comment]
@iRonin , @andy-cooper  - Can you two please have a look?  I'd like you to add some UTs for your stuff so I can do some refactor more safely.

**Comment by andy-cooper** [comment]
Sure - was away this weekend; I'll look at it this week.

**Comment by andy-cooper** [comment]
@JeffSteinbok - what are you using to run these tests? Reason I'm asking is when I configure this in IntelliJ Idea, I get two errors: the first error is that the directory hierarchy for testing should be tests/custom_components/dreo/pydreo, to mimic the actual code hierarchy (you have it simply as pydreo at a top level). The second error occurs after I attempt correct that, and then I get a bunch of errors indicative of the fact that I moved the hierarchy. Rather than go too far down that rabbit hole, I wanted to see what your setup was.

This is what I'm seeing w.r.t. directory hierarchy:

Launching pytest with arguments pydreo/test_pydreofan.py::TestPyDreoFan --no-header --no-summary -q in /Users/andy/homeassistant/hass-dreo/tests

============================= test session starts ==============================
collecting ... ERROR: found no collectors for /Users/andy/homeassistant/hass-dreo/tests/pydreo/test_pydreofan.py::TestPyDreoFan

collected 0 items / 1 error

=============================== 1 error in 0.04s ===============================

tests/pydreo/test_pydreofan.py:None (tests/pydreo/test_pydreofan.py)
pydreo/test_pydreofan.py:13: in <module>
    from imports import * # pylint: disable=W0401,W0614
pydreo/imports.py:12: in <module>
    spec.loader.exec_module(pydreo)
<frozen importlib._bootstrap_external>:936: in exec_module
    ???
<frozen importlib._bootstrap_external>:1073: in get_code
    ???
<frozen importlib._bootstrap_external>:1130: in get_data
    ???
E   FileNotFoundError: [Errno 2] No such file or directory: '/Users/andy/homeassistant/hass-dreo/tests/custom_components/dreo/pydreo/__init__.py'

**Comment by andy-cooper** [comment]
Note - I can run the tests from the command line via "pytest" from the hass-dreo directory, but that's not particularly optimal for debugging.

**Comment by JeffSteinbok** [comment]
I'm running them in Visual Studio Code as well as in the Pull Request flow automatically.

**Comment by andy-cooper** [comment]
Ok, any particular settings in VSCode?

**Comment by andy-cooper** [comment]
Hmm. So when I run it from VSCode on Mac, I now get this:

vscode_pytest.VSCodePytestError: Error attempting to connect to extension communication socket[vscode-pytest]: A test tried to use socket.socket.
ERROR conda.cli.main_run:execute(124): `conda run python /Users/andy/.vscode/extensions/ms-python.python-2024.4.1/python_files/get_output_via_markers.py /Users/andy/.vscode/extensions/ms-python.python-2024.4.1/python_files/vscode_pytest/run_pytest_script.py --rootdir /Users/andy/homeassistant/hass-dreo/tests` failed. (See above for error)

Seems to be a well-known problem with the vscode-python plugin.

**Comment by JeffSteinbok** [comment]
Ok. I would hope there's a workaround.
Failing that you can run them from the command line just fine, and as a GitHub action.

Either way, I'd like to get the UnitTest corpus growing a bit as we have more and more stuff in there that's not easily testable.

**Pull request merged**
