### PR TITLE
Some initial tests for heaters

### PR DESCRIPTION
**Pull request by andy-cooper**

### CODE REVIEW

**Comment by andy-cooper** [comment]
@JeffSteinbok some tests for you

**Comment by JeffSteinbok** [comment]
Approved.  Note it's not great practice to LOG and then Raise an error.  Just raise the error.

**Comment by andy-cooper** [comment]
Agreed. I was following your lead here: https://github.com/JeffSteinbok/hass-dreo/blob/736aca5c75fea235a6372f90e13bcbef000cc289/custom_components/dreo/pydreo/pydreofan.py#L158

**Comment by JeffSteinbok** [comment]
Yeah. I probably missed some.
Thx

-Jeff

On Aug 26, 2024, at 2:55 PM, andy-cooper ***@***.***> wrote:

﻿

Agreed. I was following your lead here: https://github.com/JeffSteinbok/hass-dreo/blob/736aca5c75fea235a6372f90e13bcbef000cc289/custom_components/dreo/pydreo/pydreofan.py#L158

**Pull request merged**
