### PR TITLE
DR-HPF004S can rotate further - -75/+75 horizontal; -30/90 vertical

### PR DESCRIPTION
**Pull request by williamg97**
DR-HPF004S has a greater range of angles than other models; therefore need to update the min/max values

### CODE REVIEW

**Comment by JeffSteinbok** [comment]
How does that impact other models?
Don't we need to adjust per model?

**Comment by williamg97** [comment]
I guess the ideal long term solution is yes adjust per model. I only have this fan so hard to say what it does to other models.

**Comment by JeffSteinbok** [comment]
Each model sends back their ranges in the api call to get their definitions. I'm working on a larger refactor and once that's done we should be able to better auto detect this stuff.

**Comment by JeffSteinbok** [comment]
Will implement this differently - We need to look at the device list and look for limits in the returned JSON.

**Pull request closed without merging**
